tip_titles = {
  "Aim Controls",
  "amiibo Rune",
  "amiibo Rune",
  "Ancient Furnaces",
  "Ancient Walls",
  "Archery Tip",
  "Armor Sets",
  "Basic Controls",
  "Battle Tip",
  "Battle Tip",
  "Battle Tip",
  "Battle Tip",
  "Battle Tip",
  "Battle Tip",
  "Battle Tip",
  "Battle Tip",
  "Battle Tip",
  "Battle Tip",
  "Battle Tip",
  "Beat the Heat",
  "Bedtime",
  "Bokoblins",
  "Bokoblins",
  "Bomb Barrels",
  "Boomerangs",
  "Bottomless Bog",
  "Burning Things",
  "Calling Your Horse",
  "Calming Your Horse",
  "Changing Focus",
  "Charged Attack",
  "Climbing Tip",
  "Climbing Tip",
  "Climbing Tip",
  "Climbing Tip",
  "Climbing Tip",
  "Cooking Pots",
  "Cooking Secrets",
  "Collecting Ingredients",
  "Cold Water",
  "Critical Hit",
  "Critical Hits",
  "Critical Hits",
  "Cryonis",
  "Cryonis",
  "Cryonis",
  "Cutting Grass",
  "Dodging Attacks",
  "Electric Chuchus",
  "Electric Lizalfos",
  "Elemental Weaknesses",
  "Elemental Weaknesses",
  "Fairy Effects",
  "Fairy Effects",
  "Falling Death",
  "Falling Death",
  "Finding Your Way",
  "Fire Arrows",
  "Fire Chuchus",
  "Fishing Tip",
  "Freezing Climates",
  "Freezing Climates",
  "Galloping",
  "Galloping",
  "Galloping",
  "Gems",
  "Goddess Statues",
  "Granter of Boons",
  "Guardians",
  "Guardians",
  "Horse Gaits",
  "Horse Steps",
  "Horse Temperaments",
  "Horse Temperaments",
  "Horseback Battles",
  "Horseback Battles",
  "Hot Springs",
  "Hyrule Compendium",
  "Ice Arrows",
  "Ice Chuchus",
  "Ingredient Effects",
  "Ingredient Effects",
  "Jump Slash",
  "Ladders",
  "Lightning Strikes",
  "Lizalfos",
  "Luring Fish",
  "Magnesis",
  "Magnesis",
  "Magnesis",
  "Making a Campfire",
  "Map Pins",
  "Map Stamps",
  "Master Sword",
  "Moblins",
  "Monster Ingredients",
  "More than a Weapon",
  "Nighttime Monsters",
  "No Stone Unturned",
  "Octo Balloon",
  "Paraglider",
  "Paraglider",
  "Perfect Dodge",
  "Perfect Guard",
  "Pools of Malice",
  "Pushing Objects",
  "Rafts",
  "Registering Horses",
  "Remote Bombs",
  "Remote Bombs",
  "Remote Bombs and Wind",
  "Resetting the Camera",
  "Resting at an Inn",
  "Restoring Hearts",
  "Roasting Ingredients",
  "Rumor has it...",
  "Rumor has it...",
  "Rumor has it...",
  "Sand Seals",
  "Sand Seals",
  "Sand Seals",
  "Scope Tip",
  "Scorching Climates",
  "Scorching Climates",
  "Scorching Climates",
  "Setting Fires",
  "Sheikah Sensor",
  "Sheikah Sensor +",
  "Shield Surfing",
  "Shock Arrows",
  "Shooting Stars",
  "Smoke Signals",
  "Special Bows",
  "Sprinting",
  "Stamina Wheel",
  "Stamina Wheel",
  "Stasis",
  "Stasis",
  "Stasis",
  "Stealth Tip",
  "Stealth Tip",
  "Strafing",
  "Swimming Tip",
  "Surviving the Cold",
  "Targeting",
  "Temperature Changes",
  "The Joys of Night",
  "The Joys of Rain",
  "The Steed Takes the Lead",
  "Throwing Weapons",
  "Time Flies",
  "Time Flies",
  "Tips and Tricks",
  "Training Your Horse",
  "Travel Gates",
  "Treetops",
  "Updrafts",
  "Weapon Bonuses",
  "Weapon Durability",
  "What's That Pooch?",
  "Where's the Fire?",
  "Wild Horses"
}

tip_text = {
  "Some items, like bows, allow you to target things by tilting       . Remember to be aware of your surroundings when doing this.",
  "Some amiibo may only be used once per day.",
  "Use an amiibo to summon forth an item that may be useful to you on your adventure!",
  "These energy furnaces glow with a blue flame. They are said to be creations of the ancient Sheikah race. It may be true, as they've been burning for 10,000 years.",
  "Shrine walls are too slick to grab or climb. You must find alternate ways to reach new heights, such as ladders or other creative solutions.",
  "Draw your bowstring while jumping from a high place to briefly slow down time so that you can aim with greater accuracy.",
  "Wearing the top, bottom, and headwear from the same set can earn you some bonus effects.",
  "Take a peek at your controls at any time by opening the  +  menu and checking under System.",
  "Monsters sometimes leave their weapons lying around their camp. Sneaking up on them and stealing these items will make defeating them much easier!",
  "If a monster is hiding behind a shield. you can bat the shield away by hitting it with a heavy sword or axe.",
  "Monsters on the lookout in watchtowers will sound the alarm if they spot you. Defeat these foes first before they alert the others.",
  "Monsters need their beauty rest too. If you see a group of monsters sleeping, use that opportunity to sneak-attack them!",
  "It's dangerous to approach enemies head-on when you're low on hearts or don't have protective armor equipped. Always be prepared!",
  "The difference between winning and losing a battle often comes down to strategy. With the right tactics, you may be able to defeat an entire group of enemies at once.",
  "Instead of throwing yourself at enemies over and over to no avail, try cooking special dishes and elixirs to give yourself better defense, extra damage, or more hearts.",
  "If an enemy camp has multiple levels, each packed with monsters, consider using the paraglider to sneak your way to the top.",
  "If the foe you're fighting is too powerful, train yourself up! You can start by finding a stronger weapon or collecting Spirit Orbs to get more hearts or increase your Stamina Wheel.",
  "Using Magnesis to toss metal objects into a camp full of monsters is a great way to do some damage.",
  "Monsters have a harder time detecting you if your press      to crouch and quietly approach them.",
  "The strong rays of the sun during a desert day will inflict damage if you're unprepared. You'll need to spend time in the shade or water or equip special armor specially made for high temperatures.",
  "Sleeping in a bed allows you to sleep until morning, noon or night, It also replenishes your hearts.",
  "Without much in the way of clothing to protect them, they tend to run when menaced by bees.",
  "These omnivorous monsters enjoy not only meat and fish but also fresh fruit.",
  "Shoot a Fire Arrow into a bomb barrel to make it explode. Tossing a burning weapon at one works too.",
  "Throw a boomerang with     , and it will fly in a large arc before returning to you. What goes around comes around!",
  "A quagmire that will draw you in...Sink in too deeply, and you'll be unable to escape.",
  "Dry grass catches ﬁre especially easily, and that fire spreads quickly.",
  "Horses you have registered are displayed on the map. If one of them is nearby, call it with      and it will come running.",
  "When a wild horse that you're riding starts to act out or ignore you, try soothing it with     . If you keep this up, it will become more obedient over time.",
  "When there are multiple things to lock on to, press      again to switch your focus.",
  "You can ready a charged attack by holding    . Doing so depletes your stamina, so be sure to time your attack carefully.",
  "Use      and     to kick off from the surface you're currently climbing. If you use the paraglider right afterward to glide, you can reach many new places.",
  "Overhangs that curve outward and the underside of ceilings are too difficult to hang on to. If you try to climb these surfaces anyway, you will fall.",
  "In rainy weather, cliffs become slippery and may not be possible to scale. Wait for clear weather before attempting to climb a steep cliff whenever possible.",
  "When you're in a hurry to climb somewhere, you can scale a wall quicker by using    . Doing so uses up a lot of stamina, so make sure you have enough left to make it to the top!",
  "The stamina required for climbing increases with the steepness of the cliff. To climb higher while using less stamina, it's important to find walls that have a gentler slope.",
  "Cook up some wild cuisine by throwing together some ingredients and seeing what happens. You can't cook with an unlit pot.",
  "Using more of an effect-imparting ingredient when cooking will increase that effect in the resulting dish.",
  "There are many more ingredients than those used for cooking food. Collect and experiment with different ingredients to make all sorts of things!",
  "Swimming in cold water will lower your body heat and cause you to take damage. Cooked food and special garb won't help you.",
  "When using a weapon with this bonus, the last hit in a series of attacks will deal double the damage.",
  "Weapons that you have no use for are perfect for throwing at monsters. If one hits, it will deal double damage.",
  "Hitting a monster or enemy in the head with an arrow deals double the normal amount of damage.",
  "Use this power to create a pillar of ice on the water's surface. Such pillars can be used for lifting objects or climbing.",
  "An ice pillar can be broken by lining your reticle up with it and pressing    .",
  "Aim at your feet with     to create an ice pillar directly beneath you. Press     again to return to the reticle.",
  "Wildlife taking shelter in the grass will sometimes jump out when you cut down their hiding place.",
  "While targeting an enemy, execute a backflip by holding      and pressing    . This move is useful for dodging enemy attacks.",
  "When you attack Electric Chuchus, they explode in a burst of sparks. Use this to your advantage to shock nearby monsters.",
  "If you hit an Electric Lizalfos's horn with an arrow, it will discharge a massive electric shock.",
  "If you use an icy attack against a fiery enemy, you may defeat it in one hit.",
  "If you use a fiery attack against an icy enemy, you may defeat it in one hit.",
  "If you keep a fairy in your pouch, it will automatically restore some hearts when you fall in battle.",
  "If you have a fairy help you cook, the tonic you produce together restores a great deal of hearts.",
  "Depending on the height, you may take damage, or even die, when you fall. Be cautious out there walking near cliff edges!",
  "Depending on the height, you may take damage, or even die, when you fall. Remember to use the paraglider for a safe descent.",
  "If you get lost, try climbing to higher ground and looking around. Press      to pull out your scope so you can see even farther.",
  "Use Fire Arrows to burn dry grass and defeat multiple enemies at the same time.",
  "When you attack Fire Chuchus, they explode and start a fire. Use this to your advantage to turn up the heat on nearby monsters.",
  "If you use     to dash while swimming, you can get up close to a school of fish before they swim away.",
  "Some ingredients will freeze if submerged in ice-cold water or when left out in frigid regions. There are a few ingredients that taste even better frozen.",
  "Wear cold-resistant clothing or eat something that warms your body when adventuring in cold climates. Otherwise, the cold will slowly chip away at your health.",
  "You can run down smaller monsters atop your galloping steed, but don't forget that you cannot make quick turns when traveling this way.",
  "Running your horse at max speed is called galloping. Press     to increase your horse's speed until it reaches a full gallop.",
  "The number of times you can increase your speed depends on each horse. If you find a horse with a high number of spurs, consider keeping it as your companion.",
  "The gems that sometimes drop when you break ore deposits fetch a high price when sold.",
  "These ancient monuments depict the Goddess worshipped in Hyrule since time out of mind. You can trade four Spirit Orbs to one for a Stamina Wheel or a Heart Container.",
  "At the far reaches of the continent, there is a being that trades in Heart Containers and Stamina Vessels.",
  "Guardians are ancient, highly advanced weapons, so items from the current age won't deal much damage. Weapons from their own era like ancient arrows are better suited to combat them.",
  "Their entire bodies are covered in armor, so low-powered weapons won't do any damage. It's best to avoid these foes until you have the right tools for the job!",
  "As your horse's speed increases—between walk, trot, canter, and gallop—their gait changes as well. Use     to increase your speed, and use      to decrease it.",
  "While totally motionless, if you press and hold     , your horse will take careful steps in any direction with     . Do this if your horse balks or when you find yourself stuck somewhere.",
  "Trying to force a rowdy an untamed horse to speed up will likely result in you being tossed to the ground.",
  "Just as some horses have a naturally wild temperament, some horses are inherently shy. If you try to approach monsters atop a shy steed, it will become frightened and try to turn away.",
  "When fighting on horseback, use      to focus your attention, making it easier to aim.",
  "When fighting on horseback, weapons with reach such as spears and big swords have an advantage over short swords and clubs.",
  "These lush, thermal baths are found throughout the world. You can relax in them for a while to replenish your hearts.",
  "Images captured with your Camera are logged in your Hyrule Compendium. Things that can be logged include wildlife, monsters, ingredients, and weapons.",
  "If you find yourself surrounded by an overwhelming number of enemies, try using Ice Arrows to freeze them in their tracks.",
  "When you attack Ice Chuchus, they explode in a burst of frost. Use this to your advantage to put nearby monsters on ice.",
  "You can only enjoy one effect from a dish or elixir at any given time. If you're relying on an active effect, be careful not to cancel it by eating something with a new effect.",
  "Certain ingredients give elixirs or dishes special properties. But don't get greedy: ingredients with different effects will cancel each other out.",
  "Perform a jump slash by pressing     after jumping or while in the air. The shock wave created when you hit the ground can affect nearby monsters.",
  "Climbing ladders will not deplete your stamina. However, using     to jump up a ladder will.",
  "Lightning has a tendency to strike anything metallic. Whenever you hear thunder, it's a good idea to remove any metallic equipment before you get fried.",
  "As carnivores, they eat meat, fish, and even insects.",
  "Tossing ingredients that serve as bait near fish in the water will attract them. Different bait works on different kinds of fish.",
  "Use this power to lift up metallic objects hidden in the water.",
  "When you find a metallic object, you can use this power to lift it up and move it around freely, regardless of how heavy it is.",
  "Use this power to swing heavy metallic objects around and drop them on top of foes as a creative attack method!",
  "To start a campfire, simply set some wood ablaze. You can use a torch or some flint to do just that.",
  "Not only can you drop pins while looking through the scope, but you can also add or delete pins from the map on your Sheikah Slate.",
  "You can stamp the map on your Sheikah Slate with reminders of important discoveries, like the location of a cooking pot or something unusual you want to investigate later.",
  "When your hearts are full, you can fire a beam from the sword with R . The more Heart Containers you have, the further the beam's range.",
  "These large carnivores require sizable helpings of meat and fish to sustain their bulky frames.",
  "If you combine monster parts dropped by fallen foes in a cooking pot with things like lizards and butterflies, you can create elixirs with special effects.",
  "Metal weapons create sparks that can be used to light a fire. Furthermore, if you set a wood weapon on fire, it can be used a torch.",
  "When night falls, skeletal Stal monsters will emerge from the ground. Stay vigilant!",
  "Wildlife taking shelter under a rock will sometimes jump out when you lift up their hiding place.",
  "When inflated, this sac obtained from defeating Octoroks is extremely buoyant. Place one near something you want to lift to make it float into the air.",
  "With the paraglider, you can glide down from high places with ease. Use      to scope out a safe spot to land.",
  "Soaring with the paraglider depletes your Stamina Wheel. Be careful to monitor your stamina so you don't run out midflight.",
  "If you backflip or side hop away from a monster's attack at just the right moment, you will be rewarded with a chance to let loose with a flurry of attacks.",
  "When equipped with a shield, if you press     to deflect a monster's attack at just the right moment, you will be rewarded with a chance to counter the attack.",
  "Poisonous bogs formed by water that was sullied during the Great Calamity. Coming into contact with one will hurt you.",
  "Barrels and boxes can be pushed around. Use this to your advantage!",
  "Rafts with sails can move when pushed by the wind. Or you can get them moving yourself if you have a Korok leaf.",
  "Once you've tamed a wild horse, you can register it by taking it to a stable. Do this, and you'll be able to call your beloved steed to your side whenever you please.",
  "The spherical bombs will roll downhill, whereas the cube-shaped bombs will not. Make sure to use the right bomb for the landscape!",
  "These bombs are useful not only for dealing damage to monster. They can also be used to break rocks and weak walls.",
  "Remote Bombs are lighter than they appear. Use the wind to your advantage to roll them in a certain direction or to blow them farther than you could throw them on your own.",
  "Press      to quickly shift the camera behind Link. If there's an object nearby that you can focus on, the camera will target it.",
  "Sleeping overnight in a bed can do more than just fully replenish your hearts. If you spend more for a comfier bed, you can temporarily increase your hearts!",
  "You can replenish your hearts by consuming fruits and veggies you've collected, as well as meat you've acquired through hunting. Eat ingredients raw or cook them to increase their healing properties.",
  "Throw ingredients like mushrooms or fish directly into a fire to roast them and up their health benefits. However, roasting an ingredient this way will cause it to lose whatever special effect it provided.",
  "Forest Spirits called Koroks like to hide in unexpected places. It is said something good will happen if you find a lot of them!",
  "If you see a flock of birds gathering in the sky, try searching the area beneath them. You might just find something interesting...",
  "Deep in the forest resides a glowing blue spirit in the form of a rabbit. It is said that whoever is skilled enough to hit it with an arrow receives a handsome reward.",
  "In order to hitch a ride behind a sand seal, you'll first need to equip a shield.",
  "These large beasts native to the Gerudo Desert are much friendlier than they look. They've been domesticated over time for use as a mode of transportation.",
  "Sand seals provide a fast way to travel across sand. When hitching a ride, be careful not to run into any rocks!",
  "When you find an object or place of interest while looking through your scope, press     to place a pin on your map in that location so you wont forget about it.",
  "In the extreme heat of volcanic regions, wooden bows or shields you have equipped will catch fire. It's better to use metal equipment instead.",
  "The extreme temperatures of volcanic regions will hurt you without the proper precautions. Wear fireproof equipment or down an elixir to stave off the heat.",
  "In the extreme heat of volcanic regions, ingredients will cook simply by placing them on the ground. Use this to your advantage to prepare meals on the go.",
  "Wooden objects and dry grass catch fire easily. Be careful around such things while holding a lit torch.",
  "Use this power to detect the location of shrines. Simply head in the direction where the reading is strongest.",
  "The Sheikah Sensor + can detect objects that are logged to your Hyrule Compendium.",
  "If you jump while your shield is out, you can climb aboard it using    . This will knock some durability off of the shield, but it's an effective way to travel downhill quickly!",
  "Shoot shock arrows into water or metallic objects to electrify enemies and monsters.",
  "If you should see a star shoot through the night sky, mark the place where it lands—you might find something there.",
  "A plume of smoke in the distance is a good sign that you might find someone at its origin.",
  "A few bows fire multiple arrows at once. They offer several times the power of normal bows, while strangely only consuming one arrow at a time.",
  "Move around while holding     to sprint. This is useful for evading monster attacks or whenever you're in a hurry.",
  "If your stamina runs out while climbing, you will lose your grip and fall.",
  "Swimming depletes your stamina. If this runs out while you're swimming, you will sink below the water and, unless you've run out of hearts, be returned to dry land.",
  "Freezing a Bomb Barrel using Stasis and then attacking it will cause it to fly off and explode at its point of impact.",
  "Attacking objects stopped by Stasis will make them build up energy. This energy will then be released once the time-halting effect ends.",
  "This power allows you to halt time for certain objects, completely stopping them in place.",
  "Crouching in a grassy field makes it harder for monsters and enemies to detect you. Keep this mind if you want to ambush enemies or avoid fighting altogether.",
  "It's harder to hear footsteps when it's raining...That makes it the perfect time to sneak up on some monsters!",
  "If you want to move side to side without changing the direction you're facing, try moving sideways while pressing     .",
  "When in the water, you can swim faster using    . Be careful not to overuse this, lest your stamina run low and you drown.",
  "Even in frigid climates, the heat of a campfire can help you warm. Holding a lit torch is another good way to stave off the cold.",
  "Press      while near an enemy to target it. When locked on to something, you can freely circle around it.",
  "The temperature will change depending on your location and the time of day. It's a good idea to pay close attention to fluctuations in temperature when you're out roaming.",
  "Some animals and insects only come out when it's dark. Keep an eye out for them!",
  "Some animals love playing in the rain, and there are certain plants that only bloom during rainstorms. Keep an eye out for them!",
  "Obedient horses will follow pathways without being told to. Leave the running up to your loyal steed every once in a while so you can enjoy the scenery!",
  "If your weapon is close to breaking, try throwing it at an enemy using     . It will double your damage if it hits!",
  "If you ever want to advance time, seek out a cozy campfire. There, you can pass the time until morning, noon, or night.",
  "Monsters thrive at nighttime—as do other things that can make adventuring dangerous. If you're low on hearts at night, find a campfire and lay low until morning.",
  "Check this screen for hints that will surely aid you on your journey. The adventuring heart must never stop seeking knowledge!",
  "Horses that you have just caught won't listen to much of what you tell them to do. The more time you spend adventuring with your steed, the better behaved it will become.",
  "You can travel instantly to shrines and towers using the map on the Sheikah Slate (   ). If there's somewhere you need to be, travel to a shrine or tower near your destination to get there faster.",
  "The things you can do atop small trees are limited, but they have their uses. Use them to scout an area with your scope. It's a handy way to decide your next destination!",
  "When fire spreads, it creates an updraft. You can use the paraglider to catch that updraft and ride it high into the sky.",
  "Some weapons you'll come across have special properties that set them apart from others of their class, such as superior durability or above-average attack power.",
  "Durability varies with every weapon. Always be aware of the condition of your equipment. A weapon breaking at the wrong time is never a good thing.",
  "If you befriend a dog, it may lead you to something interesting.",
  "When a wooden weapon or shield catches fire, you can extinguish it by unequipping the burning item.",
  "If you see a wild horse you'd like to ride, crouch down so you can approach it quietly from behind. Take heed, though—if the horse notices you while you're directly behind it, it will kick you!"
}